
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - npm test
before_script:
  - npm install jsonwebtoken
  - psql -c 'CREATE DATABASE ppltest;' -U postgres
after_success:
  - npm install coveralls && npm run coverage
