FORMAT: 1A
HOST: https://propertyproliteapi.herokuapp.com/api

# PropertyProLite

Property Pro Lite is a platform where people can create and/or search properties for sale or rent.

## Properties collection [/v2/property]

### List All properties [GET]

+ Response 200 (application/json)

        {
            "status": "200",
            "message": "properties retrieved succesfully",
            "data": [
                {
                    "id": 8,
                    "owner": 2,
                    "status": "sold",
                    "price": 90000,
                    "state": "Rwanda",
                    "city": "arusha",
                    "address": "76768",
                    "type": "apartment",
                    "createdon": "2019-07-18T13:11:42.328Z",
                    "imageurl": "https://res.cloudinary.com/hezzie/image/upload/v1561036548/PropertyProLiteAPI/2019-06-20T13:15:46.472Z.png"
                },
                {
                    "id": 10,
                    "owner": 2,
                    "status": "available",
                    "price": 7890,
                    "state": "Rwanda",
                    "city": "arusha",
                    "address": "76768",
                    "type": "atmyyyyyyyyyyent",
                    "createdon": "2019-07-18T14:13:21.574Z",
                    "imageurl": "https://res.cloudinary.com/hezzie/image/upload/v1561036548/PropertyProLiteAPI/2019-06-20T13:15:46.472Z.png"
                }
            ]
        }



## Post property [/v2/property/]

### Create a New Property [POST]

You may post your own property using this action. It takes a JSON
object containing a property name, propertytype, and an uploaded image.

+ Request (application/json)

        {
            "type": "twobedroom",
            "price": "7000",
            "state": "tanzania",
            "city": "arusha",
            "address": "76768",
            "imageurl": "https://res.cloudinary.com/hezzie/image/upload/v1561036548/PropertyProLiteAPI/2019-06-20T13:15:46.472Z.png"
        }

+ Response 201 (application/json)

    + Headers

            Location: /v2/property

    + Body

              {
                    "status": "201",
                    "message": "Property created Succesfully",
                    "data": {
                        "id": 8,
                        "owner": 2,
                        "status": "sold",
                        "price": 90000,
                        "state": "Rwanda",
                        "city": "arusha",
                        "address": "76768",
                        "type": "apartment",
                        "createdon": "2019-07-18T13:11:42.328Z",
                        "imageurl": "https://res.cloudinary.com/hezzie/image/upload/v1561036548/PropertyProLiteAPI/2019-06-20T13:15:46.472Z.png"
                    }
                }
              
## Single Property [/v2/property/:id]

### Fetch a single property [GET]

+ Response 200 (application/json)

          {
                "status": 200,
                "message": "properties retrieved succesfully",
                "data": {
                    "id": 8,
                    "owner": 2,
                    "status": "sold",
                    "price": 90000,
                    "state": "Rwanda",
                    "city": "arusha",
                    "address": "76768",
                    "type": "apartment",
                    "createdon": "2019-07-18T13:11:42.328Z",
                    "imageurl": "https://res.cloudinary.com/hezzie/image/upload/v1561036548/PropertyProLiteAPI/2019-06-20T13:15:46.472Z.png"
                }
            }


### Update property [PATCH]

You may update your own property using this action. It takes a JSON
object.

+ Request (application/json)

        {
            "type": "apartment",
            "price": "70000",
            "state": "Rwanda"
        }

+ Response 201 (application/json)

    + Headers

            Location: /v2/property/:id

    + Body

            {
                "status": 200,
                "message": "properties retrieved succesfully",
                "data": {
                    "id": 8,
                    "owner": 2,
                    "status": "sold",
                    "price": 90000,
                    "state": "Rwanda",
                    "city": "arusha",
                    "address": "76768",
                    "type": "apartment",
                    "createdon": "2019-07-18T13:11:42.328Z",
                    "imageurl": "https://res.cloudinary.com/hezzie/image/upload/v1561036548/PropertyProLiteAPI/2019-06-20T13:15:46.472Z.png"
                }
            }

## Users collection [/v2/users]

### List All users [GET]

+ Response 200 (application/json)

        {
            "status": "200",
            "message": "User retrieved succesfully",
            "data": [
                {
                    "id": 2,
                    "firstname": "hezron",
                    "lastname": "kimutai",
                    "username": "hjuye",
                    "email": "hiuuj@gmail.com",
                    "phonenumber": "8778788888",
                    "address": "979790790",
                    "isadmin": true,
                    "profilepic": null,
                    "createdon": "2019-07-19T06:36:38.801Z"
                },{
                    "id": 2,
                    "firstname": "kimutai",
                    "lastname": "hezron",
                    "username": "eizzeh",
                    "email": "efff@gmail.com",
                    "phonenumber": "8778788888",
                    "address": "979790790",
                    "isadmin": true,
                    "profilepic": null,
                    "createdon": "2019-07-19T06:36:38.801Z"
                }
            ]
        }

## Users collection [/v2/auth/signup]

### Create a New user [POST]

You may signup using this action. It takes a JSON
object containing a username and password.

+ Request (application/json)

            {
              "firstname": "hezron",
              "lastname": "kimutai",
              "username": "hjuye",
              "email": "hiuuj@gmail.com",
              "phonenumber": "8778788888",
              "address": "979790790",
              "isadmin": true,
              "password": "rtTT45$ty@"
            }

+ Response 201 (application/json)

    + Headers

            Location: /v12/auth/signup

    + Body

              {
                "firstName": "hezron",
                "secondName": "kimutai",
                "userName": "hezzie",
                "email": "hez@gmail.com",
                "phoneNumber": "0937892356",
                "password": "reqfhgtfhfgjfg",
                "id": 5209
              }


## Single user [/v1/users/:id]

### Fetch a single user [GET]

+ Response 200 (application/json)

            {
                "status": 201,
                "message": "successfully created the user",
                "data": {
                    "id": 3,
                    "firstname": "hezron",
                    "lastname": "kihmutai",
                    "username": "hhjuye",
                    "email": "hihuuj@gmail.com",
                    "phonenumber": "8178788888",
                    "address": "979790790",
                    "isadmin": true,
                    "profilepic": null,
                    "createdon": "2019-07-19T07:02:38.024Z",
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RuYW1lIjoiaGV6cm9uIiwibGFzdG5hbWUiOiJraWhtdXRhaSIsInVzZXJuYW1lIjoiaGhqdXllIiwiZW1haWwiOiJoaWh1dWpAZ21haWwuY29tIiwicGhvbmVudW1iZXIiOiI4MTc4Nzg4ODg4IiwiYWRkcmVzcyI6Ijk3OTc5MDc5MCIsImlzYWRtaW4iOnRydWUsInByb2ZpbGVwaWMiOm51bGwsImNyZWF0ZWRvbiI6IjIwMTktMDctMTlUMDc6MDI6MzguMDI0WiIsImlhdCI6MTU2MzUxOTc1OCwiZXhwIjoxNTYzNjA2MTU4fQ.LRXu4R-mJoufdx8HuH9p0IOGqZR0BF53rcv2---7jFE"
                }
            }