FORMAT: 1A
HOST: https://propertyproliteapi.herokuapp.com/api/

# PropertyProLite

Property Pro Lite is a platform where people can create and/or search properties for sale or rent.

## Get all properties [/properties]

### List All properties [GET]

+ Response 200 (application/json)

        [
            {
                "name": "samsung g4c",
                "category": "phones",
                "state": "Kenya",
                "price":"6000",
                "city":"Nairobi",
                "address":"30100",
                "map":"789,7655",
                "reason":"rent",
                "description": "None of the things will be sold",
                "url": "https://res.cloudinary.com/hezzie/image/upload/v1560592303/PropertyProLiteAPI/2019-06-15T09:51:41.924Z.png",
                "id": 2563
            },{
                "name": "mercedess benz",
                "category": "vehicles",
                "state": "Rwanda",
                "price":"6,000,000",
                "city":"Kigali",
                "address":"36100",
                "map":"789,789655",
                "reason":"sell",
                "description": "Selling this property for free",
                "url": "https://res.cloudinary.com/hezzie/image/upload/v1560592303/PropertyProLiteAPI/2019-06-15T09:51:41.924Z.png",
                "id": 2589
            }
        ]


### Get Single property [/properties/2563]

### Fetch a single property [GET]

+ Response 200 (application/json)

        {
            "name": "samsung g4c",
            "category": "phones",
            "state": "Kenya",
            "price":"6000",
            "city":"Nairobi",
            "address":"30100",
            "map":"789,7655",
            "reason":"rent",
            "description": "None of the things will be sold",
            "url": "https://res.cloudinary.com/hezzie/image/upload/v1560592303/PropertyProLiteAPI/2019-06-15T09:51:41.924Z.png",
            "id": 2563
        }
        
### Delete a Single property [/properties/2560]

### Delete a single property [DELETE]

+ Response 201 (application/json)

        <!--{-->
        <!--    "propertyName": "macerdees benz truck",-->
        <!--    "propertyType": "heavy truck",-->
        <!--    "propertyUrl": "https://res.cloudinary.com/hezzie/image/upload/v1560592303/PropertyProLiteAPI/2019-06-15T09:51:41.924Z.png",-->
        <!--    "id": 2563-->
        <!--}-->

### Post a property [/properties/post-property]
### Create a New Property [POST]

You may post your own property using this action. It takes a JSON
object.

+ Request (application/json)

        {
            "name": "samsung g4c",
            "category": "phones",
            "state": "Kenya",
            "price":"6000",
            "city":"Nairobi",
            "address":"30100",
            "map":"789,7655",
            "reason":"rent",
            "description": "None of the things will be sold",
            "url": "https://res.cloudinary.com/hezzie/image/upload/v1560592303/PropertyProLiteAPI/2019-06-15T09:51:41.924Z.png",
            "id": 2563
        }

+ Response 201 (application/json)

    + Headers

            Location: /properties/post-property

    + Body

            {
                "name": "samsung g4c",
                "category": "phones",
                "state": "Kenya",
                "price":"6000",
                "city":"Nairobi",
                "address":"30100",
                "map":"789,7655",
                "reason":"rent",
                "description": "None of the things will be sold",
                "url": "https://res.cloudinary.com/hezzie/image/upload/v1560592303/PropertyProLiteAPI/2019-06-15T09:51:41.924Z.png",
                "id": 2563
            }

### Update a property [/properties/2569]
### Update a property [PUT]

You may update your own property using this action. It takes a JSON
object.

+ Request (application/json)

        {
            "name": "samsung g4c",
            "category": "phones",
            "state": "Kenya",
            "price":"6000",
            "city":"Nairobi",
            "address":"30100",
            "map":"789,7655",
            "reason":"rent",
            "description": "None of the things will be sold",
            "url": "https://res.cloudinary.com/hezzie/image/upload/v1560592303/PropertyProLiteAPI/2019-06-15T09:51:41.924Z.png"
        }

+ Response 201 (application/json)

    + Headers

            Location: /properties/post-property

    + Body

            {
                "name": "samsung g4c",
                "category": "phones",
                "state": "Kenya",
                "price":"6000",
                "city":"Nairobi",
                "address":"30100",
                "map":"789,7655",
                "reason":"rent",
                "description": "None of the things will be sold",
                "url": "https://res.cloudinary.com/hezzie/image/upload/v1560592303/PropertyProLiteAPI/2019-06-15T09:51:41.924Z.png",
                "id": 2563
            }


## Users collection [/users]

### List All users [GET]

+ Response 200 (application/json)

        [
            {
              "username": "Katumani",
              "password": "Khj",
              "id": 8118
            },{
              "username": "Katumani",
              "password": "Khj",
              "id": 8118
            }

        ]


### Single user [/users/8118]

### Fetch a single user [GET]

+ Response 200 (application/json)

        {
          "username": "Katumani",
          "password": "Khj",
          "id": 8118
        }

### Create a New user [POST]

You may signup using this action. It takes a JSON
object containing a username and password.

+ Request (application/json)

        {
          "username": "Katumani",
          "password": "Khj",
          "id": 8118
        }

+ Response 201 (application/json)

    + Headers

            Location: /users/signup

    + Body
    
            {
              "username": "Katumani",
              "password": "Khj",
              "id": 8118
            }