FORMAT: 1A
HOST: https://propertyproliteapi.herokuapp.com/api

# PropertyProLite

Property Pro Lite is a platform where people can create and/or search properties for sale or rent.

## Properties collection [/properties]

### List All properties [GET]

+ Response 200 (application/json)

        [
              {
                "category": "Sifn fgle room",
                "name": "Houscbhfxce",
                "reason": "renfhfcbct",
                "price": "7000",
                "state": "tancbvbczania",
                "city": "arusha",
                "address": "76768",
                "map": "90800,89900",
                "description": "Very coovbvbvl house",
                "url": "https://res.cloudinary.com/hezzie/image/upload/v1561036548/PropertyProLiteAPI/2019-06-20T13:15:46.472Z.png",
                "id": 9023
              }
        ]


### Single property [v2/properties/:id]

### Fetch a single property [GET]

+ Response 200 (application/json)

          {
            "category": "Sifn fgle room",
            "name": "Houscbhfxce",
            "reason": "renfhfcbct",
            "price": "7000",
            "state": "tancbvbczania",
            "city": "arusha",
            "address": "76768",
            "map": "90800,89900",
            "description": "Very coovbvbvl house",
            "url": "https://res.cloudinary.com/hezzie/image/upload/v1561036548/PropertyProLiteAPI/2019-06-20T13:15:46.472Z.png",
            "id": 9023
          }

### Create a New Property [POST]

You may post your own property using this action. It takes a JSON
object containing a property name, propertytype, and an uploaded image.

+ Request (application/json)

          {
            "category": "Sifn fgle room",
            "name": "Houscbhfxce",
            "reason": "renfhfcbct",
            "price": "7000",
            "state": "tancbvbczania",
            "city": "arusha",
            "address": "76768",
            "map": "90800,89900",
            "description": "Very coovbvbvl house",
            "url": "https://res.cloudinary.com/hezzie/image/upload/v1561036548/PropertyProLiteAPI/2019-06-20T13:15:46.472Z.png",
          }

+ Response 201 (application/json)

    + Headers

            Location: v2/properties/post-property

    + Body

              {
                "category": "Sifn fgle room",
                "name": "Houscbhfxce",
                "reason": "renfhfcbct",
                "price": "7000",
                "state": "tancbvbczania",
                "city": "arusha",
                "address": "76768",
                "map": "90800,89900",
                "description": "Very coovbvbvl house",
                "url": "https://res.cloudinary.com/hezzie/image/upload/v1561036548/PropertyProLiteAPI/2019-06-20T13:15:46.472Z.png",
                "id": 9023
              }

### Update property [PATCH]

You may update your own property using this action. It takes a JSON
object.

+ Request (application/json)

          {
            "name": "Two bed room"
          }

+ Response 201 (application/json)

    + Headers

            Location: v2/properties/:id

    + Body

              {
                "category": "Sifn fgle room",
                "name": "Two bed room",
                "reason": "renfhfcbct",
                "price": "7000",
                "state": "tancbvbczania",
                "city": "arusha",
                "address": "76768",
                "map": "90800,89900",
                "description": "Very coovbvbvl house",
                "url": "https://res.cloudinary.com/hezzie/image/upload/v1561036548/PropertyProLiteAPI/2019-06-20T13:15:46.472Z.png",
                "id": 9023
              }

## Users collection [v2/users]

### List All users [GET]

+ Response 200 (application/json)

        [
              {
                "first_name": "hezron",
                "second_name": "kimutai",
                "user_name": "hezzie",
                "email": "hez@gmail.com",
                "phone_number": "0937892356",
                "password": "reqfhgtfhfgjfg",
                "id": 5209
              }{
                "first_name": "hezron",
                "second_name": "kimutai",
                "user_name": "hezzie",
                "email": "hez@gmail.com",
                "phone_number": "0937892356",
                "password": "reqfhgtfhfgjfg",
                "id": 5209
              }
        ]


### Single user [v2/users/8118]

### Fetch a single user [GET]

+ Response 200 (application/json)

          {
            "first_name": "hezron",
            "second_name": "kimutai",
            "user_name": "hezzie",
            "email": "hez@gmail.com",
            "phone_number": "0937892356",
            "password": "reqfhgtfhfgjfg",
            "id": 5209
          }

### Create a New user [POST]

### url [v2/users/signup]

You may signup using this action. It takes a JSON
object containing a username and password.

+ Request (application/json)

          {
            "first_name": "hezron",
            "second_name": "kimutai",
            "user_name": "hezzie",
            "email": "hez@gmail.com",
            "phone_number": "0937892356",
            "password": "reqfhgtfhfgjfg"
          }

+ Response 201 (application/json)

    + Headers

            Location: v2/users/signup

    + Body

              {
                "firstName": "hezron",
                "secondName": "kimutai",
                "userName": "hezzie",
                "email": "hez@gmail.com",
                "phoneNumber": "0937892356",
                "password": "reqfhgtfhfgjfg",
                "id": 5209
              }
+ Response
